%YAML:1.0
---
# model_path_xml: "../models/RMyolo-v7-new/RMyolov7-new.xml"
# model_path_bin: "../models/RMyolo-v7-new/RMyolov7-new.bin"

model_path_xml: "../models/RMyolov7-best-fp32/rmyolo-v7-best.xml"
model_path_bin: "../models/RMyolov7-best-fp32/rmyolo-v7-best.bin"


conf_threshold: 0.55
rect_cut: 1
boardSize_h: 7
boardSize_w: 9
squareSize: 1.5
img_count: 60
sample_period: 20
calib_yaml_path: "../config/camera_paramets.yaml"
cam_gain: 15.2
cam_exptime: 12000
framerate: 120
imshow_en: 1
debug_info: 1
armor_small_h: 50
armor_small_w: 135
armor_large_h: 50
armor_large_w: 200
